base:
  project: Electronic Component Classification
  random_state: 50
   
data:
  raw: 
    train_data: data/raw/train_data
    test_data: data/raw/test_data
  
  processed:
    train_data: data/processed/train_data
    test_data: data/processed/test_data

images_parameter:
  image_size : [224,224]
  num_processed_train_images: 20
  num_processed_test_images: 4

categories_file_path : src/categories.json
  



